name: Auto Sync Fork

on:
  schedule:
    - cron: "0 5 * * *" # Todos los días a 00:00 -05 (Perú)
  workflow_dispatch:
jobs:
  run-multi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        odoo_branch: ['16.0', '18.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: '${{matrix.odoo_branch}}'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/odoo/odoo.git || true

      - name: Fetch only upstream
        run: git fetch upstream ${{matrix.odoo_branch}}:upstream/${{matrix.odoo_branch}}

      - name: Setup git user
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream into fork
        run: git merge upstream/${{matrix.odoo_branch}} --no-edit

      - name: Push changes
        run: git push origin ${{matrix.odoo_branch}}
